site_name: Software Guidebook Exemplar
site_url: http://www.example.org
docs_dir: guidebook
dev_addr: localhost:8081
nav: 
  - Context: 
    - Context: 01-context/README.md
    - More Context: 01-context/more-context.md
    - Subcontext: 01-context/context-subfolder/more-context-in-a-subfolder.md
  - Functional Overview: 02-functional-overview/README.md
  - Quality Attributes: 03-quality-attributes/README.md
  - Constraints: 04-constraints/README.md
  - Principles: 05-principles/README.md
  - Software Architecture: 06-software-architecture/README.md
  - Code: 07-code/README.md
  - Data: 08-data/README.md
  - Infrastructure Architecture: 09-infrastrcture-architecture/README.md
  - Deployment: 10-deployment/README.md
  - Operation and Support: 11-operation-and-support/README.md
  - Development Environment: 12-development-environment/README.md
  - Decision Log: 13-decision-log/README.md
theme: readthedocs